on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:
<<<<<<< HEAD
      - name: 'Before'
        run: ls

      - uses: actions/checkout@v3
      
      - name: 'After'
        run: ls
	    
=======
      - name: 'Testing Hithub action'
        run: pwd
      - name: 'Testing Printing'
        run: echo Akram
>>>>>>> d98829e4631661dfb8e13cba38b630177f62c060
