on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'Testing Hithub action'
        run: pwd
	    - name: 'Testing Printing'
        run: echo Akram